// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Admin",
    "telepon": "087888997711",
    "email": "admin@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"

}

###
GET  http://localhost:5000/users

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:5000/Me